### ISSUE TITLE
Remove dependency to `tsdx`

### ISSUE THREAD

**Issue by lourot** [Frameright/react-image-display-control#23]
We scaffolded this project using https://github.com/jaredpalmer/tsdx, which isn't maintained anymore, leading to issues and workarounds like the `overrides` in https://github.com/Frameright/react-image-display-control/blob/main/package.json

In our `package.json` scripts calling `tsdx`, most of the time it is only a wrapper around other well-known open-source tools, so we should be able to get rid of it.

**Comment by sakibian** [comment]
Hey @AurelienLourot Can I work on this?

![image](https://github.com/Frameright/react-image-display-control/assets/40847839/77a669b1-a8d8-4ac3-a6ec-c8115e2d5276)

Just TSDX dependency removal serve the purpose here?

**Comment by lourot** [comment]
@sakibian yes, that would be great, thanks! If you remove the dependency to `tsdx` you'll have to make `npm start` and `npm run build` call different tools, see https://github.com/Frameright/react-image-display-control/blob/main/package.json#L39

So you'll have to figure out what tools `tsdx` is using under the hood

**Comment by sakibian** [comment]
OK, Can I get assigned to this? @AurelienLourot
